export const SIGN_IN_REQUEST = 'SIGN_IN_REQUEST';
export const SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS';
export const SIGN_IN_REJECT = 'SIGN_IN_REJECT';

export const SIGN_UP_REQUEST = 'SIGN_UP_REQUEST';
export const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS';
export const SIGN_UP_REJECT = 'SIGN_UP_REJECT';

// user info
export const GET_USER_INFO_REQUEST = 'GET_USER_INFO_REQUEST';
export const GET_USER_INFO_SUCCESS = 'GET_USER_INFO_SUCCESS';
export const GET_USER_INFO_REJECT = 'GET_USER_INFO_REJECT';


export const GET_USER_POSTS_REQUEST = 'GET_USER_POSTS_REQUEST';
export const GET_USER_POSTS_SUCCESS = 'GET_USER_POSTS_SUCCESS';
export const GET_USER_POSTS_REJECT = 'GET_USER_POSTS_REJECT';

// posts actions
export const CREATE_POST_REQUEST = 'CREATE_POST_REQUEST';
export const CREATE_POST_SUCCESS = 'CREATE_POST_SUCCESS';
export const CREATE_POST_REJECT = 'CREATE_POST_REJECT';

export const DELETE_POSTS_REQUEST = 'DELETE_POSTS_REQUEST';
export const DELETE_POSTS_SUCCESS = 'DELETE_POSTS_SUCCESS';
export const DELETE_POSTS_REJECT = 'DELETE_POSTS_REJECT';

export const LIKE_POSTS_REQUEST = 'LIKE_POSTS_REQUEST';
export const LIKE_POSTS_SUCCESS = 'LIKE_POSTS_SUCCESS';
export const LIKE_POSTS_REJECT = 'LIKE_POSTS_REJECT';

export const UNLIKE_POSTS_REQUEST = 'GET_USER_POSTS_REQUEST';
export const UNLIKE_POSTS_SUCCESS = 'GET_USER_POSTS_SUCCESS';
export const UNLIKE_POSTS_REJECT = 'GET_USER_POSTS_REJECT';